# Generated by Django 3.0.7 on 2020-06-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200606_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='option3',
        ),
    ]
