# Generated by Django 3.0.7 on 2020-06-06 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_option_option3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='author',
            new_name='user',
        ),
    ]
