# Generated by Django 3.0.7 on 2020-06-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200606_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leggings',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('img_src', models.TextField()),
                ('provider', models.CharField(max_length=200)),
                ('link', models.TextField()),
                ('feature', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
            ],
        ),
    ]
